import type { Verdict } from './assertions';
import { attentionSpread, DESIGNED_ENTRY_NET_PER_MINUTE, DESIGNED_NET_PER_MINUTE } from './assertions';
import type { UpgradeEffect } from './experiment';
import type { RunResult } from './types';

/**
 * What the balance run found, as something a person can read — Phase 12.
 *
 * Markdown for the argument and CSV for the curves, because they answer
 * different questions. "Did the economy stay inside its envelope" is a sentence;
 * "what does income look like minute by minute under `roi-optimal`" is a plot,
 * and a plot pasted into Markdown as a table is neither.
 *
 * The report is regenerated on every run and committed, so a config change shows
 * up as a **diff in the numbers** rather than as a claim in a commit message.
 */

function verdictLine(verdict: Verdict): string {
  const mark = verdict.notApplicable ? '⊘' : verdict.passed ? '✅' : '❌';
  const blocking = verdict.mergeBlocking ? ' **(merge-blocking)**' : '';
  return `| ${mark} | ${verdict.title}${blocking} | ${verdict.detail} |`;
}

export function markdownReport(
  runs: readonly RunResult[],
  verdicts: readonly Verdict[],
  effects: readonly UpgradeEffect[],
  generatedFor: string,
): string {
  const failures = verdicts.filter((verdict) => !verdict.passed);
  const blocked = verdicts.filter((verdict) => verdict.notApplicable);
  const totalWallClock = runs.reduce((total, run) => total + run.wallClockMs, 0);

  const lines: string[] = [];

  lines.push('# BALANCE REPORT');
  lines.push('');
  lines.push('> **Generated by `pnpm balance`. Do not edit by hand — it will be overwritten.**');
  lines.push('');
  lines.push(`**Commit:** ${generatedFor}`);
  lines.push(`**Policies:** ${runs.map((run) => run.policy).join(', ')}`);
  lines.push(`**Simulated:** ${String(runs[0]?.minutesSimulated ?? 0)} minutes per policy`);
  lines.push(`**Wall clock:** ${(totalWallClock / 1000).toFixed(1)} s for all policies`);
  lines.push('');
  lines.push(
    failures.length === 0
      ? `**Result: ✅ every evaluable assertion passed**, with ${String(blocked.length)} not evaluable.`
      : `**Result: ❌ ${String(failures.length)} assertion(s) failed.**`,
  );
  lines.push('');

  lines.push('## The ten assertions — ECONOMY_DESIGN §13');
  lines.push('');
  lines.push('| | Assertion | Measured |');
  lines.push('| --- | --- | --- |');
  for (const verdict of verdicts) lines.push(verdictLine(verdict));
  lines.push('');
  lines.push('`⊘` means **not evaluable**, which is not the same as passing: the run had');
  lines.push('nothing to look at. Every one of them is explained in §"Blocked" below.');
  lines.push('');

  lines.push('## Per policy');
  lines.push('');
  lines.push(
    '| Policy | Served | Stage 2 | Stage 3 | Stage 4 | Upgrades | Peak sustained ₡/min | Final cash |',
  );
  lines.push('| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |');
  for (const run of runs) {
    const at = (stage: number): string => {
      const minute = run.stageEnteredAtMinute[stage];
      return minute === undefined ? '—' : `${minute.toFixed(1)} min`;
    };
    lines.push(
      `| \`${run.policy}\` | ${String(run.customersServed)} | ${at(2)} | ${at(3)} | ${at(4)} | ` +
        `${String(run.upgradesBought)} | ₡${run.peakSustainedIncomePerMinute.toFixed(1)} | ` +
        `₡${run.finalCash.toFixed(0)} |`,
    );
  }
  lines.push('');

  const attention = attentionSpread(runs);
  if (attention !== null) {
    lines.push('### Attention, measured but not asserted');
    lines.push('');
    lines.push(`${attention.detail}. An idle player *should* be slower; how much slower is a`);
    lines.push('design decision nobody has taken, so this is reported rather than gated.');
    lines.push('');
  }

  lines.push('## The designed envelope — ECONOMY_DESIGN §3');
  lines.push('');
  lines.push('| Stage | Designed entry ₡/min | Designed ceiling ₡/min | Best observed (day average) |');
  lines.push('| ---: | ---: | ---: | ---: |');
  for (let stage = 1; stage <= 4; stage++) {
    const observed = runs
      .flatMap((run) => run.samples.filter((sample) => sample.stage === stage))
      .filter((sample) => sample.sustainedIncomePerMinute > 0)
      .map((sample) => sample.sustainedIncomePerMinute);
    const best = observed.length === 0 ? null : Math.max(...observed);
    lines.push(
      `| ${String(stage)} | ₡${String(DESIGNED_ENTRY_NET_PER_MINUTE[stage] ?? 0)} | ` +
        `₡${String(DESIGNED_NET_PER_MINUTE[stage] ?? 0)} | ` +
        `${best === null ? 'not reached' : `₡${best.toFixed(1)}`} |`,
    );
  }
  lines.push('');

  lines.push('## Does each upgrade earn its price?');
  lines.push('');
  lines.push('Paired experiment: two runs from the same seed, identical tick for tick, one of');
  lines.push('which buys the upgrade. The difference **is** the effect — the day curve and the');
  lines.push('arrival noise cancel because both runs saw the same ones.');
  lines.push('');
  lines.push('| Upgrade | Level | Revenue without | Revenue with | Δ |');
  lines.push('| --- | ---: | ---: | ---: | ---: |');
  for (const effect of effects) {
    const sign = effect.delta >= 0 ? '+' : '';
    lines.push(
      `| \`${effect.upgradeId}\` | ${String(effect.level)} | ₡${effect.revenueWithout.toFixed(0)} | ` +
        `₡${effect.revenueWith.toFixed(0)} | ${sign}${effect.delta.toFixed(1)} |`,
    );
  }
  lines.push('');

  lines.push('## Change requests this run raises');
  lines.push('');
  lines.push('Recorded here rather than acted on, because they change published design');
  lines.push('numbers and WORKING_DISCIPLINE §6 makes that a decision rather than an edit.');
  lines.push('');
  lines.push('1. **The average ticket and the menu prices disagree.** ECONOMY_DESIGN §3 builds');
  lines.push('   the envelope on a ₡4.50 average ticket; §4 publishes three Stage 1 prices that');
  lines.push('   average ₡3.33 under the uniform item choice the simulation implements. Phase 12');
  lines.push('   scaled the three prices *and* their ingredient costs by 1.35 to close it with');
  lines.push('   every margin unchanged. When the fourteen-item menu exists and choice is');
  lines.push('   weighted by the `appealTags` §4 already carries, they should go back to');
  lines.push('   ₡3 / ₡5 / ₡2 and the average should arrive from the mix.');
  lines.push('2. **Stages 2 to 4 have no content.** Three of fourteen menu items and five of the');
  lines.push('   upgrade tree exist. Three assertions cannot be evaluated until they do.');
  lines.push('3. **An idle player cannot progress through Stage 1.** §13 asks every policy to');
  lines.push('   reach Stage 2 inside 10–22 minutes; §5.1 makes the cook a Stage 2 role, so');
  lines.push('   Stage 1 cannot be automated at all. The two cannot both hold. Measured: 85');
  lines.push('   minutes for `idle-player` against 23 for an attentive one.');
  lines.push('4. **The game lets you evolve into a stage you cannot operate.** A stand holding');
  lines.push('   ₡804 may accept a ₡800 transition and open Stage 3 with ₡4 — too little to hire');
  lines.push('   the waiter the stage needs. Measured before the policies were taught to keep a');
  lines.push('   float: zero income, zero staff and zero customers for the remaining ten hours,');
  lines.push('   with no way back. Cash never went negative, so nothing objected.');
  lines.push('');

  if (blocked.length > 0) {
    lines.push('## Blocked — assertions with nothing to evaluate');
    lines.push('');
    for (const verdict of blocked) lines.push(`- **${verdict.title}** — ${verdict.detail}`);
    lines.push('');
  }

  return `${lines.join('\n')}\n`;
}

/** The income and pacing curves, one row per sample, for plotting. */
export function csvReport(runs: readonly RunResult[]): string {
  const rows: string[] = [
    'policy,minutes,stage,cash,net_income_per_min,sustained_income_per_min,customers_served,upgrades,employees',
  ];
  for (const run of runs) {
    for (const sample of run.samples) {
      rows.push(
        [
          run.policy,
          sample.minutes.toFixed(2),
          String(sample.stage),
          sample.cash.toFixed(2),
          sample.netIncomePerMinute.toFixed(3),
          sample.sustainedIncomePerMinute.toFixed(3),
          String(sample.customersServed),
          String(sample.upgradesBought),
          String(sample.employees),
        ].join(','),
      );
    }
  }
  return `${rows.join('\n')}\n`;
}
